### ISSUE TITLE
[Suggestion] More Customizable Guild Buffs

### ISSUE THREAD

**Issue by CraftSteamG** [guilds-plugin/Guilds#133]
## Context
Guild buffs are an amazing feature and should be more customizable, like commands to be run, instead of the default potion effects. 
## Possible Implementation

Instead of  the current implementation:

```yaml
            haste:
                # What do you want to name the buff?
                name: '&a&lSubstance of the Redmod Graff'
                # How much do you want the buff to cost?
                price: 60.0
                # How long (in second) should the buff last?
                time: 60
                # How strong do you want the buff to be? 0 = Potion Level 1, 1 = Potion Level 2, etc...
                amplifier: 0
                # What item do you want to represent the buff?
                icon: FEATHER
                # What type of potion is this?
                type: FAST_DIGGING
                # You can put as much as you want here
                description: 
                - '&aType » &7Haste'
                - '&aLength » &760 Seconds'
                - '&aCost » &7$60'
                # Do you want this buff to show in-game?
                display: true
```
maybe it could be:

```yaml
            <name>:
                display-name:
                lore:
                - line1 etc...
                price:
                icon:
                display:
                commands:
                - 'commands to be run with placeholders like %player%'
```

Thanks for reading this :)
