### ISSUE TITLE
Prevent use of formats in guild name and prefix

### ISSUE THREAD

**Issue by SrBedrock** [guilds-plugin/Guilds#263]
## Context
I think it's important because using format code in the name or prefix makes chat a mess.

Codes: &m &l &n &o &r

## Possible Implementation
Through ReGex or config?
```yml
guild:
    requirements:
        # With the default RegEx currently set, the minimum length of the prefix is 1 and the maximum is 64.
        # To change this, adjust the number and you can refer to the link below on how to modify RegEx.
        # RegEx (https://en.wikipedia.org/wiki/Regular_expression) used to only allow certain characters (default only allows alphanumeric characters).
        # To turn off the ability to use colors, remove the & from the RegEx.
        # Trying to use symbols such as Chinese ones? Try this Regex: [\u4E00-\u9FA5_a-zA-Z0-9&_\一-龥]{1,6}
        name: '[a-zA-Z0-9&]{1,64}'
        # Similar to the name, just refer above.
        prefix: '[a-zA-Z0-9&]{3,3}'
        # Would you like to include color codes signs (&b &l, etc) in the length check?
        include-color-codes: false
        allow-format-codes: false
```
