### ISSUE TITLE
`respect-wg-pvp-flag: true` Prevents guild member and ally damage globally regardless of region pvp flag.

### ISSUE THREAD

**Issue by wolfebersahd** [guilds-plugin/Guilds#270]
## Description
Setting the `respect-wg-pvp-flag:` to `false` allows guild member and ally PvP everywhere including PvP protected areas. Setting `respect-wg-pvp-flag:` to `true` blocks guild member and ally PvP everywhere regardless of WG PvP flag.

## Expected Behavior
`respect-wg-pvp-flag: false` should ignore WG PvP flags
`respect-wg-pvp-flag: true` should respect WG PvP flags

## Actual Behavior
`respect-wg-pvp-flag: true` ignore flags and prevent PvP everywhere.

## Steps to Reproduce
1. Set the appropriate configs
```yaml
    damage:
        # Do we want people in the same guild to be able to damage each other?
        guild: true
        # Do we want allies to be able to damage each other?
        ally: true
        # Do we want to respect WorldGuard flags for PVP deny?
        # This will be checked first before checking same guild and ally.
        # This is ONLY needed if you have either of the above two options to set true.
        # ONLY PUT THIS ON TRUE IF YOU HAVE WORLDGUARD INSTALLED OR YOU WILL BREAK STUFF
        respect-wg-pvp-flag: true
```
2. Create  Guild
3. Invite a member to the guilds
4. Fight that member in a PvP enabled area.

## Your Environment

* Guilds version: 3.5.3.8-BETA
* MC Version: 1.14.4 Paper & 1.12.2 Paper
* Plugin List: Too many!
