### ISSUE TITLE
Tridents cause damage to same guild members

### ISSUE THREAD

**Issue by Burchard36** [guilds-plugin/Guilds#274]
## Description
When throwing a trident at a guild member; they take damage
We have this config set to false:
```   
guild: 
    damage:
        # Do we want people in the same guild to be able to damage each other?
        guild: false
```

## Expected Behavior
expected the same be as arrows; They don't take damage from arrows but do from tridents

## Actual Behavior
Players take direct damage from tridents

## Possible Fix
Add in tridents to the damage listener event and prevent them from doing damage

## Steps to Reproduce
1. Create a new guild & have 2 members join (Only tested with 2)
2. Gather some tridents
3. Go at it with each other

## Context
Originally we were just messing around and just happened to notice this; as we are in
beta this hasn't effected us yet but some kits have tridents in them and it can potentially be an issue

## Your Environment

* Guilds version Latest (3.5.3.8)
* MC Version 1.15.1 PaperMC
* Plugin List Tried it just on vanilla with vault, luckperms world edit, guilds + world guard and does the same activity
